# Generated by Django 4.2.6 on 2023-10-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDocSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='techdoc',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='randomdocs.techdocsource'),
        ),
    ]
