# Generated by Django 4.2.6 on 2023-10-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomdocs', '0002_techdocsource_techdoc_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techdoc',
            name='source',
        ),
        migrations.RemoveField(
            model_name='techdocsource',
            name='source',
        ),
        migrations.AlterField(
            model_name='techdoc',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='techdocsource',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='TechDocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='randomdocs.techdocsource')),
            ],
            options={
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.AddField(
            model_name='techdoc',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='randomdocs.techdoccategory'),
            preserve_default=False,
        ),
    ]
