# Generated by Django 4.2.6 on 2023-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomdocs', '0003_remove_techdoc_source_remove_techdocsource_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdoc',
            name='link',
            field=models.URLField(max_length=400),
        ),
    ]
